### ISSUE TITLE
Datamodel throws error when temporal field value is left blank.

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#105]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**

I have a dataset where there are two columns (Date of Order) and (Date of payment).
This being real world data a Date of Payment field does not exists for each order due to pending payment.
I'm unable to create any charts with this data because Datamodel throws an error when a column
marked as temporal has a blank field.
Please see this simplified fiddle to replicate the behaviour

https://jsfiddle.net/r8j3zchk/

**What is the expected behavior?**
Ideally I would expect that nothing be rendered on time axis for missing entries instead of throwing error.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by ranajitbanerjee** [comment]
Fixed in #26
