### ISSUE TITLE
Show timestamps in x axis

### ISSUE THREAD

**Issue by swamu** [chartshq/muze#145]
There is no distinct bifurcation between the 1st and the 2nd tick when timestamps are shown on the x-axis (id: TC-fe476a2b848bc0ba930668346f517495).
![tick-issue](https://user-images.githubusercontent.com/14866260/52109007-01a75d80-2622-11e9-8b01-ff9ac358df28.png)

**Comment by adotg** [comment]
@swamu what's the expected behaviour?

**Comment by adarshlilha** [comment]
Resolved in #165 
Snapshot of the above sample :-
<img width="613" alt="screenshot 2019-02-12 at 1 17 09 pm" src="https://user-images.githubusercontent.com/13575704/52619797-b5cda180-2ec8-11e9-8483-f5722278c070.png">
