### ISSUE TITLE
Color legend is not removed when color field is removed from config

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#150]
*Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
After supplying color field using the `.color(field)` api , if I update the canvas config and supply an
empty string, color legend is not removed.

Please see this fiddle to reproduce behaviour
https://jsfiddle.net/vf04phcu/1/

**What is the expected behavior?**
If the color config is overridden by supplying empty string or undefined, canvas should remove
color legend

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by adarshlilha** [comment]
Fixed in #162
