### ISSUE TITLE
Breaking when doing faceting with temporal field

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#172]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
A canvas is created and passed a configuration including a temporal field vs a measure to create a line chart.
If the rows/columns(whichever has the temporal field) is updated to include another dimension,
the axis of temporal fields breaks. 
Please see this fiddle to reproduce the behaviour:
https://jsfiddle.net/spwh0xmd/

**What is the expected behavior?**
Chart should show correct temporal axes for temporal field after another dimension is added.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by mridulmeh** [comment]
Issue exists when temporal field is used as a facet.
It is not necessary to update the canvas to replicate this.
Using columns/rows as ['Year', 'Horsepower'] will also form the error.
