### ISSUE TITLE
Ordering of fields in crosstab is random

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#188]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
I'm plotting a crosstab of Year, Origin vs Horsepower using the cars dataset.
After grouping by Year the origins pane shows the origins arranged randomly in each section.

![image](https://user-images.githubusercontent.com/7683718/53330072-98aac100-3913-11e9-87c3-37d5a9cc0423.png)

**What is the expected behavior?**
Ideally the arrangement of fields  in crosstab should be consistent.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by UD-UD** [comment]
The `Origin` fields are *not* arranged randomly. It takes the order that is provided in data. If you like to see that in a particular order, do sort the data initially before passing it to Muze.

In the next release an api for sort will be added in lib config which will enable you to provide with the sorting details.

**Comment by adarshlilha** [comment]
Added an api for user to specify the fields to sort
```
.config({
    sort: {
        Origin: 'asc' || 'desc'
    }
})
```
Note:- Fields not specified by user and not sorted by muze and used as is
