### ISSUE TITLE
Unable to see all records in crossstab.

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#199]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
In a heavily populated crosstab, not all the cells are shown even after scrolling.
This happens when the crosstab shows a groupBy of more than two fields with high cardinaility.
On scrolling to the bottom of the crosstab, the records are clipped with no way to see the remaining.

Please see this fiddle.
https://jsfiddle.net/tn9vs0u1/

**What is the expected behavior?**
Scrolling should allow seeing all records.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by mridulmeh** [comment]
#182 Fixed as a part of this issue
