### ISSUE TITLE
number format not reflected in tooltip

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#222]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
Specifying a numberFormat in schema shows formatted values in axis ticks.
The same formatting is not reflected in tooltip.

**What is the expected behavior?**
The numberFormat should also be reflected in tooltip.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by ranajitbanerjee** [comment]
Fixed in #215 issue
