### ISSUE TITLE
Legend header and body spacing not appropriate

### ISSUE THREAD

**Issue by adotg** [chartshq/muze#27]
When legend is positioned at bottom, the spacing between header and body is too large which makes the header of legend feel like a part of axis.

Config
```javascript
canvas
    .data(dm)
    .width(600)
    .height(400)
    .rows(['Displacement'])
    .columns(['Horsepower'])
    .color('Origin')
    .detail(['Name'])
    .config({
        legend: {
            position: 'bottom'
        }
    })
    .mount(node) /* Attaching the canvas to DOM element */```

**Comment by sanjaymahto** [comment]
<img width="691" alt="screenshot 2019-01-16 at 9 01 06 pm" src="https://user-images.githubusercontent.com/25404832/51259746-c9bdda80-19d2-11e9-93cc-6c7edba0a9b0.png">
@mridulmeh 
1.) Legend alignment is not correct, it should be according to center matrix.
2.) spacing between the legend and axis name (Cylinders as per above image) is incorrect.
3.) distance between the y-axis and It's label, and X-axis and It's label is not Same.

**Comment by adotg** [comment]
This issue is not valid but alternate issue (#99 ) is raised to address the concerns.
