### ISSUE TITLE
tick layer showing stale tick mark after changing datamodel

### ISSUE THREAD

**Issue by jvert** [chartshq/muze#281]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
After changing the datamodel and selection, the tick mark from the old datamodel is still displayed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. You can either a scale down sample, JSFiddle or JSBin link**

https://codepen.io/jvert/full/ZEbQvdG

You will see a bar chart with min/max tick layer and average point layer. X axis is dates from Apr 6-15. The rightmost bar is selected and at the bottom you will see the corresponding date April 15 2020. Clicking different bars will single-select that bar and change the date at the bottom.

Now press the "switch" button. This will load a new dataset with dates from Mar 27-Apr 5 and the chart will animate to represent the new data. BUT there is one stale tick mark on Mar 31 which is leftover from the original dataset. You can hover or select Mar 31 and see that the min/max is 0, but the tick is still displaying 1-5 from the first dataset.

**What is the expected behavior?**

Tick mark displayed on Mar 31 is 0-0 to match the data.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**

Reproduced on FireFox 75.0 and Chrome 80.0.3987.163 on Win10.

I realize this sample is a bit convoluted. Let me explain the effect I am trying to achieve. 

Dates (by day) across the x-axis displaying a bar chart with a Count value and a tick chart displaying Min/Max/Avg data. The rightmost bar should be selected by default and the text outside the graph should display the selected date/min/max/avg data as text. I also want the single select behavior (only one date at a time can be selected) so I started from the SingleSelectBehaviour example in the documentation (under RegisterBehaviours)

There is probably a simpler way to get the behaviour I want but this is my first time using Muze and all the behavior/side effect/firebolt action stuff is pretty hard to figure out. Right now I have everything working except the weird stray tick mark which has been driving me crazy!

**Comment by ranajitbanerjee** [comment]
Thanks for raising the issue. This is a bug in muze which will be fixed in next release.

For now, you can set `interactive: false` in tick layer to overcome this issue. I have created a codepen sample for the same. 
https://codepen.io/chartshq/full/bGVpLVQ

Also, I am dispatching the `singleSelect` behaviour on `canvas.drawn` which triggers before the animation starts.

**Comment by jvert** [comment]
thanks for the quick response, that workaround fixes my issue!
