### ISSUE TITLE
Add TypeScript Type Definition

### ISSUE THREAD

**Issue by Mohammed90** [chartshq/muze#35]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Doesn't include type definition file.

**What is the expected behavior?**

A TypeScript type definition file (*.d.ts) is present to aid developers who are using the library with TypeScript. It can also work as a proof of correctness.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**

v1.0.3

**Comment by adotg** [comment]
For completeness [similar issue in DataModel](https://github.com/chartshq/datamodel/issues/6) also needs to get fixed.

**Comment by adotg** [comment]
@Mohammed90 Nope, earlier version of Muze did not have this feature.
