### ISSUE TITLE
Sorting a groupedBy DataModel does not render in a chart

### ISSUE THREAD

**Issue by swapsCAPS** [chartshq/muze#39]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Sorting a groupedBy DataModel does not work.
![screenshot](https://user-images.githubusercontent.com/1317131/47093830-4998a500-d22a-11e8-80ad-c543b1db6869.png)

**Example**
```coffeescript
import _    from "underscore"
import m    from "moment"
import muze from "muze"

{ DataModel }     = muze
{ groupBy, sort } = DataModel.Operators

schema = [
	{
		name:     "total"
		type:     "measure"
		defAggFn: "avg"
	}
	{
		name:    "start"
		type:    "dimension"
		subtype: "temporal"
	}
	{
		name:    "day"
		type:    "dimension"
		subtype: "datetime"
		format:  "%d"
	}
]

data = [
	{ total: 5, start: m().subtract(1, "days") }
	{ total: 4, start: m().subtract(4, "days") }
	{ total: 9, start: m().subtract(1, "days") }
	{ total: 1, start: m().subtract(4, "days") }
	{ total: 8, start: m().subtract(3, "days") }
	{ total: 6, start: m().subtract(2, "days") }
	{ total: 2, start: m().subtract(3, "days") }
	{ total: 3, start: m().subtract(2, "days") }
]

data = _.map data, (d) ->
	_.extend {}, d,
		start: +d.start
		day:   m(d.start).format "DD"

# data = _.sortBy data, "day" # Sorting dataset here first gives expected result

groupFn = groupBy ["day"], total: "avg"
sortFn  = sort    [ "day", "ASC" ]

dm = new DataModel data, schema

dm = groupFn sortFn dm # Switching these around doesn't work either

canvas
	.data    dm
	.width   600
	.height  450
	.rows    [ "total" ]
	.columns [ "day" ]
	.mount   "#chart-container"
```

**What is the expected behavior?**
![screenshot_deux](https://user-images.githubusercontent.com/1317131/47093945-7f3d8e00-d22a-11e8-830c-1f52c88a542e.png)

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
1.0.3 Chrome

Also is it possible to use the DataModel to group by date range? It's vaguely mentioned in the docs but I couldn't find anything about it. Is adding a key like I do above the correct approach?
Cheers!

**Comment by adotg** [comment]
@swapsCAPS https://jsfiddle.net/a72zypv1/4/ this works?

**Comment by swapsCAPS** [comment]
This issue can be closed. It works fine. I missed the nested array in the sort operator **doh!** Sorry!

**Comment by adotg** [comment]
My bad. In this example, you don't need groupBy since all the `day` values are unique. But imagine if you have repetition of values then `groupBy` is needed for aggregation.
