### ISSUE TITLE
Uncaught TypeError when passed empty array

### ISSUE THREAD

**Issue by swapsCAPS** [chartshq/muze#44]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`Uncaught TypeError: Cannot read property 'axisLabelDim' of null` when passed empty array

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. You can either a scale down sample, JSFiddle or JSBin link**
https://jsfiddle.net/grmzvejL/

**What is the expected behavior?**
Renders empty chart

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
Chrome - Muze 1.0.3

**Comment by UD-UD** [comment]
Already fixed in develop.
No error this thrown when canvas initialized with null data.
