### ISSUE TITLE
Simple number display and table on canvas.

### ISSUE THREAD

**Issue by timjp87** [chartshq/muze#78]
Hello,

is it currently possible to render a simple number display for example to present a KPI?
If we take the car dataset imagine creating a dashboards with multiple visuals. I want to display a measure at the top with title "Cars with more than 50 Horsepower: **67**". It would be nice if this box which just displays the number also allows interactivity so that when you click on the 67 all charts e.g. "Cars by Origin Barchart" now show only this subset.

Can I do that with a text layer? Similarly would this number display work in a pivot table like in the crosstab example: https://www.charts.com/muze/examples/view/microcharts-in-table-using-crosstab 

I was able to remove the bars in each cell, but now I have no elements to click on. If that is not the case I would open the feature request in the feedback.

Thanks!

Tim

**Comment by timjp87** [comment]
@adotg Wow thanks a lot! I'm really impressed by Muze I was looking for a DC.js alternative and found it. With KPI and Pivot Tables I think it will satisfy all by Business Intelligence needs.

**Comment by adotg** [comment]
@timjp87 We have tried to understand and address your concern and created the following fiddles

[https://codepen.io/ranajitbanerjee1992/pen/bOmmBm](https://codepen.io/ranajitbanerjee1992/pen/bOmmBm)
[https://codepen.io/ranajitbanerjee1992/full/dwggVz](https://codepen.io/ranajitbanerjee1992/full/dwggVz)

Please let us know if you want anything more out of this.

**Comment by timjp87** [comment]
@adotg This is exactly what I was looking for! I guess I will create two number displays where one is always showing the total without filter so that the user is able to reset the active filter. Maybe I create something to make it more visible which filters are currently active.

Thanks again, you are a star! :)
I am sure this is generally useful and could be added to the example section.

**Comment by adotg** [comment]
Thanks for kindness. Do let me know of you have any issues / improvements/ feedback in mind

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
