### ISSUE TITLE
Tooltip with time series chart does not show correct date string

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#79]
**Issue Type *bug***

**What is the current behavior?**
When plotting a temporal field against a measure, if I hover or select a point the tooltip does
not show the correct date string. Please see attached screen shot.
![image](https://user-images.githubusercontent.com/7683718/50962640-b1d8e900-14f0-11e9-81dd-80e1fa30bcd3.png)

If the datamodel specifies the date string as "18-04-2018" then the tooltip should show
the correct date not just "2018"

Using the latest version of muze.

**Comment by UD-UD** [comment]
Fixed as part of DataModel Date Parsing.
[DataModel PR](https://github.com/chartshq/datamodel/pull/43)

PFA below screenshot

<img width="701" alt="screenshot 2019-01-18 at 10 05 02 am" src="https://user-images.githubusercontent.com/16508993/51366033-65516700-1b09-11e9-8f92-6081210645cc.png">
