### ISSUE TITLE
Crosstab visualization does not scroll when viewport is not large enough

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#81]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
When a crosstab is plotted with a small width and height, not all the cells are rendered.
The crosstab does not have a scrollbar to allow for viewing the cells that are not rendered.

**What is the expected behavior?**
The remaining cells should become visible when I scroll.

**Comment by adotg** [comment]
Now that the scroll is present, the scroll sometimes appears in places where it shouldn't have. For all those cases scroll does not work.
Example: https://www.charts.com/muze/examples/view/gradient-legend
