### ISSUE TITLE
Stacked Bar chart rendering instead of Grouped Bar chart

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#82]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
When the average of a measure is plotted against a dimension and colored by another dimension,
a stacked bar chart is rendered.
Ideally a grouped bar chart should be shown when the measure has `defAggFn`(aggregation function) set to 'average'.
![image](https://user-images.githubusercontent.com/7683718/50964266-ca4b0280-14f4-11e9-8f68-48ed9ac5e270.png)

**What is the expected behavior?**
Grouped bar chart should be rendered.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by adotg** [comment]
Default behaviour:
Show stacked bar chart only when aggregation method is `sum`
Show grouped bar chart when the aggregation method is everything but `sum`.
