### ISSUE TITLE
Using tickFormat in axes configuration breaks rendering of temporal field

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#83]
**Do you want to request a *feature* or report a *bug*?**
* bug

**What is the current behavior?**
If the tick format config for axes is used to change the appearance of numeric fields, the 
rendering of temporal fields breaks and shows the complete JS Date string.

Before changing tickFormat the temporal axis shows properly and the y-axis shows numbers as is.
![image](https://user-images.githubusercontent.com/7683718/50964587-adfb9580-14f5-11e9-8386-213e73c21cbb.png)

After changing the tickFormat to render numbers as a local string (ex 10000 becomes 10,000) date time values are rendered as date strings.
![image](https://user-images.githubusercontent.com/7683718/50964717-02067a00-14f6-11e9-97af-fb84ed15f7ed.png)

The tickFormat configuration is as follows:
        axes: {
          x: {
            tickFormat: (value) => {
              if (typeof value === 'number') {
                return new Intl.NumberFormat().format(value);
              }
              return value;
            },
          },
          y: {
            tickFormat: (value) => {
              if (typeof value === 'number') {
                return new Intl.NumberFormat().format(value);
              }
              return value;
            },
          },
        },
You can see the behaviour in this fiddle.

https://jsfiddle.net/kv8g1q92/

**What is the expected behavior?**
Date strings should not be broken by specifying tick format.

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by sushrut141** [comment]
not fixed with desired outcome.

**Comment by rousan** [comment]
Updated specs for tickformat argument list:

```javascript
axes: {
	x: {
		tickFormat: (parsedValue, rawValue, tickIndex, ticks) => {
			// parsedValue: The value which is going to show as ticks if not modified.
			// rawValue: The actual value stored in datamodel, example: date
			// timestamp for temporal
			// tickIndex: The index of current one in ticks
			// ticks: All tick values 
		}
	}
}
```
