### ISSUE TITLE
Interactivity is slow when dataset is very large.

### ISSUE THREAD

**Issue by sushrut141** [chartshq/muze#84]
**Do you want to request a *feature* or report a *bug*?**
* improvement

**What is the current behavior?**
When tested with a dataset with 7000 rows and 21 columns, interactivity is slow.
Hovering over a bar shows the tooltip after a delay of almost 1 second.
I can't share the dataset, but the behaviour is visible in this giph I created.

![alt text](https://media.giphy.com/media/QKBb2bLwjgK6z2Qs75/giphy.gif "slow tooltip")

**What is the expected behavior?**
Can interaction be made faster with large datasets?

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**
* latest

**Comment by adotg** [comment]
Data: https://docs.google.com/a/fusioncharts.com/spreadsheets/d/1TJPh8EiOAiDiVb3KBl0Ygjo1oNZIvQlc3Q5cNtrfins/edit?usp=slack&ts=5c37197c
