### ISSUE TITLE
Layout breaks in certain cases on mobile and zoom

### ISSUE THREAD

**Issue by mridulmeh** [chartshq/muze#91]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Layout breaks when zoomed or changed display on mobile

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. You can either a scale down sample, JSFiddle or JSBin link**

**What is the expected behavior?**

There should not be any breaking

**Which versions of MuzeJS, and which browser/OS are affected by this issue? Did this work in previous versions of MuzeJS?**

All versions

**Comment by ranajitbanerjee** [comment]
This issue was occuring in this sample
https://codepen.io/ranajitbanerjee/pen/xopwzd

But it seems fixed in the latest release. @adarshlilha Please check it in various conditions in mobile, if ok then resolve the issue.
